config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"

  resources :combatants, only: %i[create update] do
    member do
      patch :delete
    end
  end

  resources :combat_trackers, only: %i[index new create edit update] do
    collection do
      get :deleted
    end

    member do
      post :add_creature
      post :restore
      post :delete
    end
  end

  resources :creatures, only: [:index]

  resources :klasses, only: [:index]

  get 'pages/home'

  resources :spells, only: %i[index search]

  get "/.well-known/acme-challenge/:id" => "letsencrypt#authenticate_key"
end

app/models/combat_tracker.rb
class CombatTracker < ApplicationRecord
  belongs_to :user
  has_many :combatants, autosave: true
  accepts_nested_attributes_for :combatants

  def combatants_by_init
    combatants.order(init: :desc)
  end

  def mark_deleted
    self.deleted = true
  end

  def self.deleted
    unscoped.where.not(deleted_at: nil)
  end

  def self.not_deleted_for(user)
    where(deleted_at: nil).where(user_id: user.id)
  end

  def soft_delete
    self.deleted_at = Time.zone.now
    save
  end

  def restore
    self.deleted_at = nil
    save!
  end

  def deleted?
    deleted_at != nil
  end

  def add_creatures(creature_id, qty)
    creatures = Creature.build_stats(creature_id, qty)
    return unless creatures

    creatures.each do |c|
      combatants.build c
      save!
    end
  end
end

app/controllers/combat_trackers_controller.rb
class CombatTrackersController < ApplicationController
  active_tab "combat_tracker"

  def index
    @new_combat_tracker = CombatTracker.new
    @combat_trackers = CombatTracker.not_deleted_for(current_user)
  end

  def new
    @combat_tracker = CombatTracker.new
  end

  def create
    ct = CombatTracker.create! combat_tracker_params.merge(user_id: current_user.id)

    redirect_to edit_combat_tracker_path(ct)
  end

  def edit
    ct = CombatTracker.find(params[:id])
    redirect_to combat_trackers_path unless current_user.can_edit_tracker?(ct)

    @combat_tracker = ct
    @creatures = Creature.all.collect { |c| [c.name, c.id] }
  end

  def update
    ct = current_user.update_combat_tracker(combat_tracker_params)

    if ct
      redirect_to edit_combat_tracker_path(ct), flash: { success: "Tracker updated!" }
    else
      redirect_to :back, alert: ct.errors.full_messages.to_sentence
    end
  end

  def restore
    ct = CombatTracker.find(params[:id])
    ct.restore

    redirect_to combat_trackers_path, flash: { success: "Tracker successfully restored!" }
  end

  def destroy
    ct = CombatTracker.find(params[:id])
    redirect_to combat_trackers_path unless current_user.can_edit_tracker?(ct)

    if ct.soft_delete
      redirect_to combat_trackers_path, flash: { success: "Tracker successfully deleted!" }
    else
      redirect_to :back, alert: ct.errors.full_messages.to_sentence
    end
  end

  def deleted
    @new_combat_tracker = CombatTracker.new
    @combat_trackers = CombatTracker.deleted

    render :index
  end

  def add_creature
    add_params = add_creature_params
    ct = CombatTracker.find(add_params[:id])
    ct.add_creatures(add_params[:creature_id], add_params[:creature_qty])

    redirect_to edit_combat_tracker_path(ct)
  end

  private

  def add_creature_params
    params.permit(:id, :creature_id, :creature_qty)
  end

  def combat_tracker_params
    params.require(:combat_tracker).permit(:id, :name, combatants_attributes: %i[id name init max_hp hp ac dc])
  end
end

app/views/combat_trackers/_add_combatant_modal.html.erb
<div id="add-combatant-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add Combatant</h4>
      </div>

      <%= ct_form.fields_for :combatants, combat_tracker.combatants.build do |new_combatant| %>
        <div class="modal-body">
          <h3>Combatant Info</h3>

          <div class="row">
            <div class="form-group col-xs-10">
              <%= new_combatant.label :name %>
              <%= new_combatant.text_field :name, class: "form-control" %>
            </div>
          </div>

          <div class="row">
            <div class="form-group col-xs-2">
              <%= new_combatant.label :init %>
              <%= new_combatant.text_field :init, { type: "number", class: "form-control" } %>
            </div>

            <div class="form-group col-xs-2">
              <%= new_combatant.label :max_hp, "Max HP" %>
              <%= new_combatant.text_field :max_hp, { type: "number", class: "form-control" } %>
            </div>

            <div class="form-group col-xs-2">
              <%= new_combatant.label :hp, "HP" %>
              <%= new_combatant.text_field :hp, { type: "number", class: "form-control" } %>
            </div>

            <div class="form-group col-xs-2">
              <%= new_combatant.label :ac, "AC" %>
              <%= new_combatant.text_field :ac, { type: "number", class: "form-control" } %>
            </div>

            <div class="form-group col-xs-2">
              <%= new_combatant.label :dc, "Spell DC" %>
              <%= new_combatant.text_field :dc, { type: "number", class: "form-control" } %>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <%= new_combatant.submit "Save", class: "btn btn-primary" %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/combat_trackers/_combatant-row-template.html.erb
<script type="text/x-tmpl" id="combatant-row-template">
  <tr class="combatant-row">
    <td class="col-xs-4"><input name="combat_tracker[combatants_attributes][replace_this][name]" class="name form-control" /></td>
    <td><input type="number" name="combat_tracker[combatants_attributes][replace_this][init]" class="init form-control" /></td>
    <td><input type="number" name="combat_tracker[combatants_attributes][replace_this][max_hp]" class="max_hp form-control" /></td>
    <td><input type="number" name="combat_tracker[combatants_attributes][replace_this][hp]" class="hp form-control" /></td>
    <td><input type="number" name="combat_tracker[combatants_attributes][replace_this][ac]" class="ac form-control" /></td>
    <td><input type="number" name="combat_tracker[combatants_attributes][replace_this][dc]" class="dc form-control" /></td>
  </tr>
</script>

app/views/combat_trackers/_combatant_cards.html.erb
<% combat_tracker.combatants_by_init.each do |combatant| %>
  <div class="row">
    <div class="combatant-card bottom20 col-lg-6 col-sm-9 col-12">
      <%= hidden_field_tag :id, combatant.id %>

      <div class="row">
        <div class="col-xs-4 col-sm-3">
          <h3 class="top10 bottom0">Init: <%= combatant.init %></h3>
        </div>

        <div class="col-xs-8 col-sm-9 text-right">
          <h3 class="top10 bottom0"><%= combatant.name %></h3>
        </div>
      </div>

      <hr class="combatant-hr top5 bottom5">

      <div class="row">
        <div class="col-xs-6">
          <strong>Armor Class</strong> <%= combatant.ac %><br/>
          <strong>HP</strong> <%= combatant.max_hp %><br/>
          <strong>Spell DC</strong> <%= combatant.dc %><br/>
        </div>

        <div class="col-xs-6">
          <h4 class="top0 text-right">Current HP</h4>

          <h4 class="top0 bottom0 pull-right">
            <%= link_to combatant_path(id: combatant.id, combatant: {hp: combatant.hp + 1}), method: :patch, class: 'btn btn-primary btn-sm', :remote => true do %>
              <span class="glyphicon glyphicon-menu-up"></span>
            <% end %>

            &nbsp;
            <span id="current-hp"><%= combatant.hp %></span>
            &nbsp;

            <%= link_to combatant_path(id: combatant.id, combatant: {hp: combatant.hp - 1}), method: :patch, class: 'btn btn-primary btn-sm', :remote => true do %>
              <span class="glyphicon glyphicon-menu-down"></span>
            <% end %>
          </h4>
        </div>
      </div>

      <% if combatant.creature.present? %>
        <hr class="combatant-hr top5 bottom5">

        <div class="row">
          <div class="col-xs-2 text-center">
            <strong>STR</strong><br/>
            <%= combatant.creature.str %> (<%= combatant.creature.str_mod_with_symbol %>)
          </div>
          <div class="col-xs-2 text-center">
            <strong>DEX</strong><br/>
            <%= combatant.creature.dex %> (<%= combatant.creature.dex_mod_with_symbol %>)
          </div>
          <div class="col-xs-2 text-center">
            <strong>CON</strong><br/>
            <%= combatant.creature.con %> (<%= combatant.creature.con_mod_with_symbol %>)
          </div>
          <div class="col-xs-2 text-center">
            <strong>INT</strong><br/>
            <%= combatant.creature.int %> (<%= combatant.creature.int_mod_with_symbol %>)
          </div>
          <div class="col-xs-2 text-center">
            <strong>WIS</strong><br/>
            <%= combatant.creature.wis %> (<%= combatant.creature.wis_mod_with_symbol %>)
          </div>
          <div class="col-xs-2 text-center">
            <strong>CHA</strong><br/>
            <%= combatant.creature.cha %> (<%= combatant.creature.cha_mod_with_symbol %>)
          </div>
        </div>
      <% end %>

      <hr class="combatant-hr top5 bottom5">

      <div class="row">
        <div class="col-md-12 bottom5 top0">
          <button id="<%= combatant.id %>" class="btn btn-primary edit-combatant-btn" data-toggle="modal" data-target="#edit-combatant-<%= combatant.id %>">
            <span class="glyphicon glyphicon-pencil"></span>
          </button>

          <%= link_to delete_combatant_path(combatant.id), :method => :patch, class: "btn btn-danger pull-right", data: confirm(title: "Delete combatant?") do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render partial: "combat_trackers/edit_combatant_modal", locals: { combatant: combatant } %>
<% end %>

app/views/combat_trackers/_combatants_cards.html.erb
<% combat_tracker.combatants_by_init.each do |combatant| %>
  <div class="row">
    <div class="combatant-card bottom20 col-md-6">
      <%= hidden_field_tag :id, combatant.id %>

      <div class="row">
        <div class="col-md-3">
          <h3 class="top10 bottom0">Init: <%= combatant.init %></h3>
        </div>

        <div class="col-md-9 text-right">
          <h3 class="top10 bottom0"><%= combatant.name %></h3>
        </div>
      </div>

      <hr class="top5 bottom5">

      <div class="row">
        <div class="col-md-6">
          Armor Class: <%= combatant.ac %><br/>
          HP: <%= combatant.max_hp %><br/>
          Spell DC: <%= combatant.dc %><br/>
        </div>

        <div class="col-md-6">
          <h4 class="top0 text-right">Current HP</h4>

          <h4 class="top0 bottom0 pull-right">
            <%= link_to combatant_path(id: combatant.id, combatant: {hp: combatant.hp + 1}), method: :patch, class: 'btn btn-default btn-sm', :remote => true do %>
              <span class="glyphicon glyphicon-menu-up"></span>
            <% end %>

            &nbsp;
            <span id="current-hp"><%= combatant.hp %></span>
            &nbsp;

            <%= link_to combatant_path(id: combatant.id, combatant: {hp: combatant.hp - 1}), method: :patch, class: 'btn btn-default btn-sm', :remote => true do %>
              <span class="glyphicon glyphicon-menu-down"></span>
            <% end %>
          </h4>
        </div>
      </div>

      <% if combatant.creature.present? %>
        <hr class="top5 bottom5">

        <div class="row">
          <div class="col-md-2 text-center">
            <strong>STR</strong><br/>
            <%= combatant.creature.str %> (<%= combatant.creature.str_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>DEX</strong><br/>
            <%= combatant.creature.dex %> (<%= combatant.creature.dex_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>CON</strong><br/>
            <%= combatant.creature.con %> (<%= combatant.creature.con_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>INT</strong><br/>
            <%= combatant.creature.int %> (<%= combatant.creature.int_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>WIS</strong><br/>
            <%= combatant.creature.wis %> (<%= combatant.creature.wis_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>CHA</strong><br/>
            <%= combatant.creature.cha %> (<%= combatant.creature.cha_mod_with_symbol %>)
          </div>
        </div>
      <% end %>

      <hr class="top5 bottom5">

      <div class="row">
        <div class="col-md-12 bottom5 top0">
          <button id="<%= combatant.id %>" class="btn btn-primary edit-combatant-btn" data-toggle="modal" data-target="#edit-combatant-<%= combatant.id %>">
            <span class="glyphicon glyphicon-pencil"></span>
          </button>

          <%= link_to delete_combatant_path(combatant.id), :method => :patch, class: "btn btn-danger pull-right", data: confirm(title: "Delete combatant?") do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render partial: "combat_trackers/edit_combatant_modal", locals: { combatant: combatant } %>
<% end %>

app/views/combat_trackers/_combatants_table.html.erb
<table class="table table-striped combatant-table data-table no-paging sort-1-desc">
  <thead>
    <tr>
      <td>Name</td>
      <td>Init</td>
      <td>Max HP</td>
      <td>HP</td>
      <td>AC</td>
      <td>Spell DC</td>
      <td>Actions</td>
    </tr>
  </thead>

  <tbody>
    <% combat_tracker.combatants.each do |combatant| %>
      <tr class="combatant-row">
        <td class="col-xs-4"><%= combatant.name %></td>
        <td><%= combatant.init %></td>
        <td><%= combatant.max_hp %></td>
        <td><%= combatant.hp %></td>
        <td><%= combatant.ac %></td>
        <td><%= combatant.dc %></td>
        <td>
          <div class="btn-group">
            <button id="<%= combatant.id %>" class="edit-combatant-btn btn btn-primary" data-toggle="modal" data-target="#edit-combatant-<%= combatant.id %>">
              <span class="glyphicon glyphicon-pencil"></span>
            </button>
             <%= link_to delete_combatant_path(combatant.id), :method => :patch, class: "btn btn-danger", data: confirm(title: "Delete combatant?") do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </div>
        </td>
      </tr>

      <%= render partial: "combat_trackers/edit_combatant_modal", locals: { combatant: combatant } %>
    <% end %>
  </tbody>
</table>

app/views/combat_trackers/_combatants_table2.html.erb
<% combat_tracker.combatants_by_init.each do |combatant| %>
  <div class="row">
    <div class="combatant-card bottom20 col-lg-6">
      <%= hidden_field_tag :id, combatant.id %>

      <div class="row">
        <div class="col-md-3">
          <h3 class="top10 bottom0">Init: <%= combatant.init %></h3>
        </div>

        <div class="col-md-9 text-right">
          <h3 class="top10 bottom0"><%= combatant.name %></h3>
        </div>
      </div>

      <hr class="top5 bottom5">

      <div class="row">
        <div class="col-lg-6">
          Armor Class: <%= combatant.ac %><br/>
          HP: <%= combatant.max_hp %><br/>
          Spell DC: <%= combatant.dc %><br/>
        </div>

        <div class="col-lg-6">
          <h4 class="top0 text-right">Current HP</h4>

          <h4 class="top0 bottom0 pull-right">
            <%= link_to combatant_path(id: combatant.id, combatant: {hp: combatant.hp + 1}), method: :patch, class: 'btn btn-secondary btn-sm', :remote => true do %>
              <span class="glyphicon glyphicon-menu-up"></span>
            <% end %>

            &nbsp;
            <span id="current-hp"><%= combatant.hp %></span>
            &nbsp;

            <%= link_to combatant_path(id: combatant.id, combatant: {hp: combatant.hp - 1}), method: :patch, class: 'btn btn-secondary btn-sm', :remote => true do %>
              <span class="glyphicon glyphicon-menu-down"></span>
            <% end %>
          </h4>
        </div>
      </div>

      <% if combatant.creature.present? %>
        <hr class="top5 bottom5">

        <div class="row">
          <div class="col-md-2 text-center">
            <strong>STR</strong><br/>
            <%= combatant.creature.str %> (<%= combatant.creature.str_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>DEX</strong><br/>
            <%= combatant.creature.dex %> (<%= combatant.creature.dex_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>CON</strong><br/>
            <%= combatant.creature.con %> (<%= combatant.creature.con_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>INT</strong><br/>
            <%= combatant.creature.int %> (<%= combatant.creature.int_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>WIS</strong><br/>
            <%= combatant.creature.wis %> (<%= combatant.creature.wis_mod_with_symbol %>)
          </div>
          <div class="col-md-2 text-center">
            <strong>CHA</strong><br/>
            <%= combatant.creature.cha %> (<%= combatant.creature.cha_mod_with_symbol %>)
          </div>
        </div>
      <% end %>

      <hr class="top5 bottom5">

      <div class="row">
        <div class="col-md-12 bottom5 top0">
          <button id="<%= combatant.id %>" class="btn btn-primary edit-combatant-btn" data-toggle="modal" data-target="#edit-combatant-<%= combatant.id %>">
            <span class="glyphicon glyphicon-pencil"></span>
          </button>

          <%= link_to delete_combatant_path(combatant.id), :method => :patch, class: "btn btn-danger pull-right", data: confirm(title: "Delete combatant?") do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render partial: "combat_trackers/edit_combatant_modal", locals: { combatant: combatant } %>
<% end %>

app/views/combat_trackers/_edit_combatant_modal.html.erb
<div id="edit-combatant-<%= combatant.id %>" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit Combatant</h4>
      </div>

      <%= form_for combatant do |c| %>
        <div class="modal-body">
          <h3>Combatant Info</h3>

          <div class="row">
            <div class="form-group col-xs-10">
              <%= c.label :name %>
              <%= c.text_field :name, class: "form-control" %>
            </div>
          </div>

          <div class="row">
            <div class="form-group col-xs-2">
              <%= c.label :init %>
              <%= c.text_field :init, { type: "number", class: "form-control" } %>
            </div>

            <div class="form-group col-xs-2">
              <%= c.label :max_hp, "Max HP" %>
              <%= c.text_field :max_hp, { type: "number", class: "form-control" } %>
            </div>

            <div class="form-group col-xs-2">
              <%= c.label :hp, "HP" %>
              <%= c.text_field :hp, { type: "number", class: "form-control" } %>
            </div>

            <div class="form-group col-xs-2">
              <%= c.label :ac, "AC" %>
              <%= c.text_field :ac, { type: "number", class: "form-control" } %>
            </div>

            <div class="form-group col-xs-2">
              <%= c.label :dc, "Spell DC" %>
              <%= c.text_field :dc, { type: "number", class: "form-control" } %>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <%= c.submit "Save", class: "btn btn-primary" %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/combat_trackers/_new_combat_tracker_modal.html.erb
<div id="new-combat-tracker-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Combat Tracker</h4>
      </div>

      <%= form_for combat_tracker do |ct| %>
        <div class="modal-body">
          <div class="row">
            <div class="form-group col-xs-10">
              <%= ct.label :name %>
              <%= ct.text_field :name, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <%= ct.submit "Save", class: "btn btn-primary" %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/combat_trackers/_new_combatant_row.html.erb
<script type="text/x-tmpl" id="combatant-row-template">
  <tr class="combatant-row">
    <td class="col-xs-4"><input name="combat_tracker[combatants_attributes][][name]" class="name form-control" /></td>
    <td><input type="number" name="combatant[init]" class="init form-control" /></td>
    <td><input type="number" name="combatant[max_hp]" class="max_hp form-control" /></td>
    <td><input type="number" name="combatant[hp]" class="hp form-control" /></td>
    <td><input type="number" name="combatant[ac]" class="ac form-control" /></td>
    <td><input type="number" name="combatant[dc]" class="dc form-control" /></td>
    <td>
      <button class="pull-right btn btn-danger btn-xs delete-row">
        <span class="glyphicon glyphicon-trash"></span>
      </button>
    </td>
  </tr>
</script>

app/views/combat_trackers/_tabs.html.erb
<div class="row">
  <div class="col-xs-6">
    <ul class="nav nav-pills">
      <%= tab("Active Trackers", combat_trackers_path, params[:action] != "deleted") %>
      <%= tab("Deleted Trackers", deleted_combat_trackers_path, params[:action] == "deleted") %>
    </ul>
  </div>

  <div class="col-xs-6">
    <div class="pull-right">
      <button type="button" class="btn btn-success"  data-toggle="modal" data-target="#new-combat-tracker-modal">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create
      </button>
    </div>
  </div>
</div>

app/views/combat_trackers/edit.html.erb
<% content_for :title, "Edit Crombat Tracker" %>

<% content_for :content do %>
  <%= form_for @combat_tracker, method: :patch do |f| %>
    <%= hidden_field_tag "combat_tracker[id]", @combat_tracker.id %>
    <div class="form-inline">
      <div class="row">
        <div class="col-12">
          <%= f.label :name %>:
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
    </div>

    <h4>Combatants information</h4>

    <div class="row">
      <div class="col-12">
        <% if @combat_tracker.present? && @combat_tracker.combatants.present? %>
          <%= render partial: "combat_trackers/combatant_cards", locals: { combat_tracker: @combat_tracker } %>
        <% else %>
          <p>There are currently no combatants in this combat tracker.</p>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div class="form-inline">
          <%= select("creature", "creature_id", @creatures, {}, { class: "form-control" } ) %>
          <%= select("quantity", "qty", (1..10), {}, { class: "creature_qty form-control", style: "width: 4em" } ) %>
          <button id="add-creature" type="button" class="btn btn-secondary">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Creature
          </button>
          <%= hidden_field_tag :id, @combat_tracker.id %>
        </div>
      </div>
    </div>

    <br/>

    <%= render partial: "combat_trackers/add_combatant_modal", locals: { ct_form: f, combat_tracker: @combat_tracker } %>

    <div class="row">
      <div class="col-12">
        <div class="form-inline">
          <button type="button" class="btn btn-secondary"  data-toggle="modal" data-target="#add-combatant-modal">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Combatant
          </button>
        </div>
      </div>
    </div>

    <br/>

    <div class="row">
      <div class="col-12">
        <div class="form-group">
          <%= button_tag "Save", type: "submit", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/combat_trackers/index.html.erb
<% content_for :title, "Combat Tracker" %>

<% content_for :content do %>
  <%= render partial: "combat_trackers/tabs" %>
  <%= render partial: "combat_trackers/new_combat_tracker_modal", locals: { combat_tracker: @new_combat_tracker }%>

  <div>
    <% if @combat_trackers.present? %>
      <div class="row">
        <div class="col-12">
          <table class="table table-hover table-striped data-table sort-2-desc no-paging">
            <thead>
              <tr>
                <td>Name</td>
                <td>Date Created</td>
                <td>Date Updated</td>
                <td>Actions</td>
              </tr>
            </thead>

            <tbody>
              <% @combat_trackers.each do |tracker| %>
                <tr class="tracker" data-tracker-id="<%= tracker.id %>" data-href="<%= edit_combat_tracker_path(tracker) %>">
                  <td class="col-xs-5"><%= tracker.name %></td>
                  <td><%= tracker.created_at.strftime('%x') %> @ <%= tracker.created_at.strftime('%r') %></td>
                  <td><%= tracker.updated_at.strftime('%x') %> @ <%= tracker.updated_at.strftime('%r') %></td>
                  <td class="col-xs-1">
                    <% if tracker.deleted? %>
                      <%= link_to restore_combat_tracker_path(tracker), method: :post, type: :button, class: "btn btn-success" do %>
                        <span class="glyphicon glyphicon-plus"></span>
                      <% end %>
                    <% else %>
                      <%= link_to combat_tracker_path(tracker), method: :delete, type: :button, class: "btn btn-danger" do %>
                        <span class="glyphicon glyphicon-trash"></span>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% else %>
      <div>
        There are currently no combat trackers.
      </div>
    <% end %>

  </div>
<% end %>