config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"

  resources :combatants, only: %i[create update] do
    member do
      patch :delete
    end
  end

  resources :combat_trackers, only: %i[index new create edit update] do
    collection do
      get :deleted
    end

    member do
      post :add_creature
      post :restore
      post :delete
    end
  end

  resources :creatures, only: [:index]

  resources :klasses, only: [:index]

  get 'pages/home'

  resources :spells, only: %i[index search]

  get "/.well-known/acme-challenge/:id" => "letsencrypt#authenticate_key"
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :creature

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combat_tracker.rb
class CombatTracker < ApplicationRecord
  belongs_to :user
  has_many :combatants, autosave: true
  accepts_nested_attributes_for :combatants

  def combatants_by_init
    combatants.order(init: :desc)
  end

  def mark_deleted
    self.deleted = true
  end

  def self.deleted
    unscoped.where.not(deleted_at: nil)
  end

  def self.not_deleted_for(user)
    where(deleted_at: nil).where(user_id: user.id)
  end

  def soft_delete
    self.deleted_at = Time.zone.now
    save
  end

  def restore
    self.deleted_at = nil
    save!
  end

  def deleted?
    deleted_at != nil
  end

  def add_creatures(creature_id, qty)
    creatures = Creature.build_stats(creature_id, qty)
    return unless creatures

    creatures.each do |c|
      combatants.build c
      save!
    end
  end
end

app/models/combatant.rb
class Combatant < ApplicationRecord
  # :name, :init, :max_hp, :hp, :ac, :dc
  belongs_to :creature
  belongs_to :combat_tracker

  before_save :strip_name

  private

  def strip_name
    name.strip if name
  end
end

app/models/creature.rb
class Creature < ApplicationRecord
  has_many :combatants
  has_many :traits
  has_many :actions
  has_many :reactions
  has_many :legendary_actions

  before_save :update_modifiers

  validates :name, uniqueness: true

  STAT_COLS = %w[str dex con int wis cha].freeze
  STAT_MOD_COLS = %w[str_mod dex_mod con_mod int_mod wis_mod cha_mod].freeze

  def self.build_stats(creature_id, qty)
    results = []
    creature = Creature.find creature_id

    (1..qty.to_i).each do |n|
      creature_name = creature.name
      creature_name += " #{n}" if qty.to_i > 1
      results << { creature_id: creature.id,
                   name: creature_name,
                   init: Roll.d20 + creature.dex_mod,
                   max_hp: creature.hp,
                   hp: creature.hp,
                   ac: creature.ac }
    end

    results
  end

  def str_mod_with_symbol
    str_mod >= 0 ? "+#{str_mod}" : str_mod.to_s
  end

  def dex_mod_with_symbol
    dex_mod >= 0 ? "+#{dex_mod}" : dex_mod.to_s
  end

  def con_mod_with_symbol
    con_mod >= 0 ? "+#{con_mod}" : con_mod.to_s
  end

  def int_mod_with_symbol
    int_mod >= 0 ? "+#{int_mod}" : int_mod.to_s
  end

  def wis_mod_with_symbol
    wis_mod >= 0 ? "+#{wis_mod}" : wis_mod.to_s
  end

  def cha_mod_with_symbol
    cha_mod >= 0 ? "+#{cha_mod}" : cha_mod.to_s
  end

  private

  def update_modifiers
    update_str_mod
    update_dex_mod
    update_con_mod
    update_int_mod
    update_wis_mod
    update_cha_mod
  end

  def update_str_mod
    self.str_mod = modifier(str) if str.present?
  end

  def update_dex_mod
    self.dex_mod = modifier(dex) if dex.present?
  end

  def update_con_mod
    self.con_mod = modifier(con) if con.present?
  end

  def update_int_mod
    self.int_mod = modifier(int) if int.present?
  end

  def update_wis_mod
    self.wis_mod = modifier(wis) if wis.present?
  end

  def update_cha_mod
    self.cha_mod = modifier(cha) if cha.present?
  end

  def modifier(score)
    (score - 10) / 2
  end
end

app/models/legendary_action.rb
class LegendaryAction < ApplicationRecord
  belongs_to :creature

  validates :name, :desc, presence: true
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :creature

  validates :name, :desc, presence: true
end

app/models/roll.rb
class Roll
  def self.d4
    rand(1..4)
  end

  def self.d6
    rand(1..6)
  end

  def self.d8
    rand(1..8)
  end

  def self.d10
    rand(1..10)
  end

  def self.d20
    rand(1..20)
  end

  def self.d100
    rand(1..100)
  end
end

app/models/spell.rb
class Spell < ApplicationRecord
  validates :level, :name, :description, :klass, presence: true

  # rubocop:disable Metrics/CyclomaticComplexity
  def self.all_for_display(klass = nil, name = nil)
    klass.capitalize! if klass
    name.downcase! if name
    klass_and_name = klass.present? && name.present?

    return where("? = ANY (klass)", klass.to_s).where("lower(name) ILIKE ?", "%#{name}%") if klass_and_name
    return where("? = ANY (klass)", klass.to_s) if klass.present?
    return where("lower(name) ILIKE ?", "%#{name}%") if name.present?
    all
  end
end

app/models/trait.rb
class Trait < ApplicationRecord
  belongs_to :creature

  validates :name, :desc, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :registerable,
         :trackable, :validatable, :lockable, :confirmable
  has_many :combat_trackers

  validate :password_is_complex

  include Users::CombatTrackerManipulator

  def password_is_complex
    return if password.nil?
    return if password =~ /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/
    errors.add(:password, "must have at least a letter, capital letter, and digit")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private_class_method def self.active_tab(tab, *options)
    before_action(*options) { @active_tab = tab }
  end
end

app/controllers/combatants_controller.rb
class CombatantsController < ApplicationController
  def create
    combatant_params = combatant_params

    Combatant.create! combatant_params

    redirect_to edit_combat_tracker_path(combatant_params[:combat_tracker_id])
  end

  def update
    combatant = Combatant.find(params[:id])

    if combatant.update(combatant_params)
      redirect_to edit_combat_tracker_path(combatant.combat_tracker_id)
    else
      redirect_to edit_combat_tracker_path(ct), alert: ct.errors.full_messages.to_sentence
    end
  end

  def delete
    combatant = Combatant.find(params[:id])

    if combatant.destroy
      msg = "Tracker successfully deleted!"
      redirect_to edit_combat_tracker_path(combatant.combat_tracker_id), flash: { success: msg }
    else
      redirect_to :back, alert: combatant.errors.full_messages.to_sentence
    end
  end

  private

  def combatant_params
    params.require(:combatant).permit(:combat_tracker_id, :name, :init, :max_hp, :hp, :ac, :dc)
  end
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  skip_before_action :authenticate_user!

  active_tab "creatures"

  def index
    @creatures = Creature.includes(:actions, :traits).all
  end
end

app/controllers/letsencrypt_controller.rb
class LetsencryptController < ApplicationController
  skip_before_action :authenticate_user!

  def authenticate_key
    render text: "#{params[:id]}.#{ENV['LETSENCRYPT_KEY']}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  skip_before_action :authenticate_user!

  active_tab "spells"

  def index
    @spells = Spell.all_for_display(params[:klass], params[:name]).order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :success
      "alert-success"
    when :error
      "alert-danger"
    when :alert, :notice, :warning
      "alert-warning"
    when :info
      "alert-info"
    end
  end

  def confirm(title:, message: "Are you sure?", fade: true)
    {
      confirm: message,
      confirm_fade: fade,
      confirm_title: title
    }
  end

  def tab(label, path, active)
    render partial: "common/tab", locals: { label: label, path: path, active: active }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
  def spells_page_title(params)
    return "#{params[:klass]} Spells" if params[:klass].present?
    "All Spells"
  end
end

app/views/characters/edit.html.erb
<% content_for :title, "Edit #{@character.name}" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :content do %>
  <%= form_for @character do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :hp, "HP(max)" %>
      <%= f.text_field :max_hp, { type: "number", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= f.label :ac, "AC" %>
      <%= f.text_field :ac, { type: "number", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= f.label :spell_dc, "Spell DC" %>
      <%= f.text_field :spell_dc, { type: "number", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= button_tag "Save", type: "submit", class: "btn btn-secondary" %>
    </div>
  <% end %>
<% end %>

app/views/common/_combat_row.html.erb
<%= form_for combatant do |c| %>
  <tr>
    <td class="col-xs-4"><%= c.text_field :name, class: "form-control" %></td>
    <td><%= c.text_field :init, class: "form-control" %></td>
    <td><%= c.text_field :max_hp, class: "form-control" %></td>
    <td><%= c.text_field :hp, class: "form-control" %></td>
    <td><%= c.text_field :ac, class: "form-control" %></td>
    <td><%= c.text_field :dc, class: "form-control" %></td>
    <td class="col-xs-2">
      <div class="btn-group" role="group" aria-label="...">
        <%= link_to combatant_path(combatant), method: :update, type: :button, class: "btn btn-primary", authenticity_token: true do %>
          Update
        <% end %>
        <%= link_to combatant_path(combatant), method: :delete, type: :button, class: "btn btn-danger", authenticity_token: true do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </div>
    </td>
  </tr>
<% end %>

app/views/common/_contents.html.erb
<div class="row no-print-border">
  <div class="col-12">
    <div class="content well">
      <%= content_for(:content) %>
    </div>
  </div>
</div>

<% next_content = 2 %>
<% while content_for(:"content_#{next_content}").present? %>
  <div class="row well">
    <%= content_for(:"content_#{next_content}") %>
  </div>

  <% next_content += 1 %>
<% end %>

app/views/common/_flash.html.erb
<% local_assigns.fetch(:messages, flash).each do |type, messages| %>
  <% Array.wrap(messages).each do |message| %>
    <% if message.present? %>
      <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible bottom0" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= message %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'TekkedOut D&D', root_path, :class => 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <%= tab('Combat Tracker', combat_trackers_path, active == 'combat_tracker') %>
        <% end %>

        <%= tab('Creatures', creatures_path, active == 'creatures') %>

        <%= tab('Spells', spells_path, active == 'spells') %>

      </ul>

      <% if user_signed_in? %>
        <div class="btn-toolbar my-2 my-lg-0">
          <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: 'btn btn-primary', role: 'button' %>
          <%= link_to 'My Account', edit_user_registration_path, class: 'btn btn-primary', role: 'button' %>
        </div>
      <% else %>
        <div class="btn-toolbar my-2 my-lg-0">
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary col-12 col-md-6', role: 'button' %>
          <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-link col-12 col-md-6', role: 'button' %>
        </div>
      <% end %>
    </div>

  </div>
</nav>

app/views/common/_tab.html.erb
<li class="nav-item  <%= 'active' if active %>">
  <%= link_to label, path, class: 'nav-link' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D&amp;D 5e Tools</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowreorder/1.2.4/css/rowReorder.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.2/css/responsive.dataTables.min.css">

    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/rowreorder/1.2.4/js/dataTables.rowReorder.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/responsive/2.2.2/js/dataTables.responsive.min.js"></script>
  </head>
  <body>
    <%= render partial: "common/navbar", locals: { active: @active_tab } %>

    <%= content_for(:jumbotron) %>

    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= render partial: "common/flash" %>

          <% if content_for(:content).present? || content_for(:sidebar).present? %>
            <div class="row">
              <% if content_for(:sidebar).present? %>
                <div class="col-lg-2 col-md-3 sidebar sidebar-left sidebar-animate sidebar-md-show">
                  <%= content_for(:sidebar) %>
                </div>
              <% end %>

              <div class="<%= content_for(:content_size).present? ? content_for(:content_size) : 'col-12' %>">
                <%= render partial: "common/contents" %>
              </div>
            </div>
          <% else %>
            <div class="mt-2">
              <%= yield %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <footer class="footer bg-dark">
      <div class="container">
        <div class="row small">
          <div class="col-md">
            Twitter: <%= link_to "@TekHudson", "https://twitter.com/TekHudson" %><br/>
            Repo: <%= link_to "tekHudson/tekkedout-dnd-tools", "https://github.com/tekHudson/tekkedout-dnd-tools" %>
          </div>

          <div class="col-md">
            Made with &lt;3 and Rails 5 by Tek Hudson<br/>
            <%= link_to "MINISWAN", "http://blog.steveklabnik.com/posts/2011-08-19-matz-is-nice-so-we-are-nice" %>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<% content_for :jumbotron do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome to TekkedOut D&amp;D</h1>

      <p>
        The items contained are a set of tools I created for use during my first campaign as a DM.
      </p>

      <p>
        This is NOT a replacement for the purchase of original Wizards of the Coast Dungeons &amp; Dragons material. Please support Wizards of the Coast by purchasing their content if you find this information helpful while playing.
      </p>

      <h3>
        This site is in Beta!
      </h3>

      <p>
        -- This database may be reset without warning --
        <br/>
        -- I will do my best to maintain user accounts --
      </p>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col">
      <h2>Updates</h2>

      <p>
        For issues please visit my repo at <%= link_to "github.com/tekHudson/tekkedout-dnd-tools", "https://github.com/tekHudson/tekkedout-dnd-tools" %>
      </p>

      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Spell Auto Search</h5>
          <h6 class="card-subtitle mb-2 text-muted">July 2018</h6>
          <p>The spells page was a little less functional than I prefered. I added an auto search as you type feature.</p>
        </div>
      </div>

      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Update to Rails 5.2 & More</h5>
          <h6 class="card-subtitle mb-2 text-muted">June 2018</h6>
          <p>Update modal for creatures to look like a statblock in the Monster Manual.</p>
          <p>Updating to newer technology stack and improving look. Also want to make certain features accessable to those who don't have accounts.</p>
          <p>I've made the decision to open up Creatures and Spells up for use by non logged participants.</p>
        </div>
      </div>

      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Bootstrap and style</h5>
          <h6 class="card-subtitle mb-2 text-muted">July 2017</h6>
          <p>Time to make it look a bit more pretty.</p>
        </div>
      </div>

      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Spin up Spells and Combat Tracker</h5>
          <h6 class="card-subtitle mb-2 text-muted">Rest of June 2017</h6>
          <p>Adding alot more functionality.</p>
        </div>
      </div>

      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Deploy to Heroku</h5>
          <h6 class="card-subtitle mb-2 text-muted">June 9th, 2017</h6>
          <p>Got it started on Heroku.</p>
        </div>
      </div>

      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">Initial commit!</h5>
          <h6 class="card-subtitle mb-2 text-muted">June 3rd, 2017</h6>
          <p>Having had frustrations with aspect of data when DMing I started work on this project.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/races/index.html.erb
<% content_for :title, "Races" %>

<% content_for :content do %>
  <p>PC: I would like to add race information to the site.</p>
  <p>DM: Give me a web coding roll.</p>
  <p>PC: ... uh ...</p>
  <p>DM: What is it gun powder merchant Vincent.</p>
  <p>PC: Natural 1.</p>
  <p>DM: In your excitement to add the race information you forget to pray to <a href="https://en.wikipedia.org/wiki/List_of_Greyhawk_deities#Delleb">Delleb</a> and as he smites you for your insolence it ignites...</p>
  <p>PC: NOT ANOTHER FINGER!!!</p>
  <p>DM: ...a trail of powder on the floor. It crackles and sizzles and apears to go out...</p>
  <p>PC: Oh man I thought I was gonna loose ano...</p>
  <p>DM: ... IT REIGNITES and streaks accross the floor to a small pot which explodes next to your foot. You loose a toe.</p>
<% end %>